# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - arnoldtec

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build with dotnet
      run: dotnet build --configuration Release --source ${{env.DOTNET_ROOT}}/FitnessTrackerSln/FitnessTracker/

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'arnoldtec'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1fd7d733c20344b8af6f1f912a8cbcfe }}
        package: ${{env.DOTNET_ROOT}}/myapp 
